version: 2.1 # use CircleCI 2.1

aliases:
  - &working_directory ~/next-pokedex-app
  - &restore_dependency_cache
    keys:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - dependency-cache-v1-{{ checksum "package-lock.json" }}
  - &save_dependency_cache
    key: dependency-cache-v1-{{ checksum "package-lock.json" }}
    paths:
      - ./node_modules

defaults: &defaults
  working_directory: *working_directory # directory where steps will run
  docker: # run the steps with Docker
    - image: circleci/node:10.13.0-browsers # ...with this image as the primary container; this is where all `steps` will run

jobs: # a collection of steps
  install:
    <<: *defaults
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: *restore_dependency_cache # special step to restore the dependency cache
      - run:
          name: install-npm
          command: npm install
      - save_cache: *save_dependency_cache # special step to save the dependency cache
      - run:
          name: build
          command: npm run build
          # Persist the specified paths (.next) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: *working_directory
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *working_directory
      - run: # run tests
          name: test
          command: npm run test:ci
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
