version: 2.1 # use CircleCI 2.1

aliases:
  - &working_directory ~/next-pokedex-app
  - &restore_dependency_cache
    keys:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - v1-dependencies-{{ checksum "package-lock.json" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  - &save_dependency_cache
    key: v1-dependencies-{{ checksum "package-lock.json" }}
    paths:
      - node_modules
      - ~/.cache

defaults: &defaults
  working_directory: *working_directory # directory where steps will run
  docker: # run the steps with Docker
    - image: circleci/node:10.13.0-browsers # ...with this image as the primary container; this is where all `steps` will run

jobs: # a collection of steps
  install:
    <<: *defaults
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: *restore_dependency_cache # special step to restore the dependency cache
      - run:
          name: Install NPM
          command: npm install
      - save_cache: *save_dependency_cache # special step to save the dependency cache
      - run:
          name: Build app
          command: npm run build
          # Persist the specified paths (.next) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: *working_directory
          paths:
            - .next
  e2e:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - restore_cache: *restore_dependency_cache # special step to restore the dependency cache
      - run:
          name: Start
          background: true
          command: npm start
      - run:
          name: Wait-on
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Cypress tests
          command: npm run cypress:run
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_dependency_cache # special step to restore the dependency cache
      - run: # run unit tests
          name: Run Jest tests
          command: npm run test:ci
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - e2e:
          requires:
            - install
